#!/bin/bash
while true; do
    sinks=$(pacmd list-sink-inputs | grep "application.name = " | grep -vE "librespot|spotify|WEBRTC VoiceEngine")
    if [[ -n "$sinks" ]]; then
        if [ "$(echo "$sinks" | wc -l)" -eq 1 ]; then
            if [[ "$(playerctl --player=vlc,mpv status 2>/dev/null)" != "Paused" ]]; then
                echo "RESETTING: mpv/vlc is not paused"
                xscreensaver-command -deactivate
                xset s reset
            fi
        else
            echo "RESETTING: something other than mpv/vlc is producing a sound"
            xscreensaver-command -deactivate
            xset s reset
        fi
    fi

    sound_output=$(pactl info | grep -Pc '^(?=.*Default Sink)(?=.*game)')
    # monitor = 0
    if [ "$sound_output" -eq 0 ]; then
        sinks=$(pacmd list-sink-inputs | grep "application.name = ")
        if [[ -n "$sinks" ]]; then
          if [ "$(echo "$sinks" | wc -l)" -eq 1 ]; then
              if [[ "$(playerctl --player=vlc,mpv status 2>/dev/null)" != "Paused" ]]; then
                  echo "RESETTING: monitor output - mpv/vlc is not paused"
                  xscreensaver-command -deactivate
                  xset s reset
              fi
          else
              echo "RESETTING: monitor output - something other than mpv/vlc is producing a sound"
              xscreensaver-command -deactivate
              xset s reset
          fi
        fi
    fi

    # keep screen active indefinitely
    # xset s reset

    sleep 10
done


